version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: rodmidde/jenkins-slave-node
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: lint
          command: npm run lint
      - run:
          name: build
          command: npm run build
      - run:
          name: test
          command: npm test
      - store_artifacts:
          path: coverage
          prefix: coverage
